# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  dotnetBuildConfiguration: 'Release'
  dotnetSolutionPath: './api/MarbleCollectorApi.sln'

steps:
- script: dotnet build $(dotnetSolutionPath) --configuration $(dotnetBuildConfiguration)
  displayName: 'dotnet build $(dotnetBuildConfiguration)'

- script: dotnet publish $(dotnetSolutionPath) /nologo /p:PublishProfile=$(dotnetBuildConfiguration) /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:DeployIisAppPath="marblecollector-api"
  displayName: 'dotnet publish as zip'
  
- task: AzureRmWebAppDeployment@4
  displayName: 'dotnet deploy to Azure'
  inputs:
    ConnectionType: 'PublishProfile'
    PublishProfilePath: '$(System.DefaultWorkingDirectory)/api/**/*.pubxml'
    PublishProfilePassword: '$(dotnetAzureAppPassword)'
    packageForLinux: '$(System.DefaultWorkingDirectory)/api/**/*.zip'

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    command: 'ci'
    workingDir: './client'
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    workingDir: './client'
    customCommand: 'run build'

