# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  dotnetBuildConfiguration: 'Release'
  dotnetSolutionPath: './api/MarbleCollectorApi.sln'

steps:
- script: dotnet build $(dotnetSolutionPath) --configuration $(dotnetBuildConfiguration)
  displayName: 'dotnet build $(dotnetBuildConfiguration)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(a2bcdf72-b2d2-4aff-a317-85e0bb318f1a)'
    appType: 'webApp'
    WebAppName: 'marblecollector-api'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- task: AzureAppServiceManage@0
  displayName: 'restart azure app service'
  inputs:
    azureSubscription: 'Azure for Students(a2bcdf72-b2d2-4aff-a317-85e0bb318f1a)'
    Action: 'Restart Azure App Service'
    WebAppName: 'marblecollector-api'

- task: Npm@1
  displayName: 'npm ci'
  inputs:
    command: 'ci'
    workingDir: './client'
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    workingDir: './client'
    customCommand: 'run build'

- task: AzureFileCopy@4
  displayName: 'deploy frontend to azure'
  inputs:
    SourcePath: './client/build/*'
    azureSubscription: 'Azure for Students(a2bcdf72-b2d2-4aff-a317-85e0bb318f1a)'
    Destination: 'AzureBlob'
    storage: 'marblecollector'
    ContainerName: '$web'